name: app_cuida_pet
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_modular: ^5.0.3
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  asuka: ^2.1.0
  dio: ^5.2.0+1
  flutter_screenutil: ^5.8.4
  firebase_core: 2.14.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.3.0
  build_runner: ^2.4.5

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: CuidapetIcons
      fonts:
        - asset: assets/fonts/CuidapetIcons.ttf