// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxoqBwCXnetI9oRCu3j1DCOI25_ueWGHs',
    appId: '1:483132674321:android:e96ce06a67d9c73c91bcb0',
    messagingSenderId: '483132674321',
    projectId: 'cuidapet-front',
    storageBucket: 'cuidapet-front.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0rDC9mT444oljH9FUouVtXgzcexEtFDk',
    appId: '1:483132674321:ios:a85e70124c074d9b91bcb0',
    messagingSenderId: '483132674321',
    projectId: 'cuidapet-front',
    storageBucket: 'cuidapet-front.appspot.com',
    androidClientId: '483132674321-e8e08djja7mobo2vmoc26boiqbl0odtf.apps.googleusercontent.com',
    iosClientId: '483132674321-qc7dvg15gb22oicqis6fsb1culvo55i6.apps.googleusercontent.com',
    iosBundleId: 'com.jbsilva.dev.cuidapet',
  );
}
